/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class FrmMenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnWebCheckin = new javax.swing.JButton();
        btnEstadoVuelo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCompraTiquetes = new javax.swing.JMenu();
        btnReservas = new javax.swing.JMenu();
        btnPromociones = new javax.swing.JMenu();
        btnDestinos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Pictures\\Logo_VivaColombia inicio.jpg")); // NOI18N

        btnWebCheckin.setText("Web Check-in");
        btnWebCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebCheckinActionPerformed(evt);
            }
        });

        btnEstadoVuelo.setText("Estado Del Vuelo");

        btnCompraTiquetes.setText("Compra tus Tiquetes");
        btnCompraTiquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompraTiquetesMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnCompraTiquetes);

        btnReservas.setText("Reservas");
        jMenuBar1.add(btnReservas);

        btnPromociones.setText("Promociones");
        jMenuBar1.add(btnPromociones);

        btnDestinos.setText("Destinos");
        btnDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinosActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnDestinos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnWebCheckin)
                .addGap(43, 43, 43)
                .addComponent(btnEstadoVuelo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWebCheckin)
                    .addComponent(btnEstadoVuelo))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDestinosActionPerformed

    private void btnCompraTiquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraTiquetesMouseClicked
        // TODO add your handling code here:

        FrmReservas abrir = new FrmReservas();
        abrir.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnCompraTiquetesMouseClicked

    private void btnWebCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebCheckinActionPerformed
        // TODO add your handling code here:

        FrmWebCheckin abrir = new FrmWebCheckin();
        abrir.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnWebCheckinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnCompraTiquetes;
    private javax.swing.JMenu btnDestinos;
    private javax.swing.JButton btnEstadoVuelo;
    private javax.swing.JMenu btnPromociones;
    private javax.swing.JMenu btnReservas;
    private javax.swing.JButton btnWebCheckin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
